<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="RegressionTest" duration-ms="17011" started-at="2020-06-22T07:29:05Z" finished-at="2020-06-22T07:29:22Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="17011" started-at="2020-06-22T07:29:05Z" finished-at="2020-06-22T07:29:22Z">
      <class name="com.framework.testcases.TC_001_Validate_Login_Page">
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.framework.testcases.TC_001_Validate_Login_Page@61001b64]" name="beforeMethod" is-config="true" duration-ms="7" started-at="2020-06-22T12:59:05Z" finished-at="2020-06-22T12:59:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.testcases.TC_001_Validate_Login_Page.TC_001_Validate_Login_Page(java.util.Hashtable) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC_001_Validate_Login_Page(java.util.Hashtable)[pri:0, instance:com.framework.testcases.TC_001_Validate_Login_Page@61001b64]" name="TC_001_Validate_Login_Page" duration-ms="14818" started-at="2020-06-22T12:59:05Z" data-provider="getData" finished-at="2020-06-22T12:59:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Status=PASS, Password=Jakay07@, Runmode=Y, Expected_Result=Jakay N, Email=josephkuruvilla891@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Jakay N] but found [Jakay M]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Jakay N] but found [Jakay M]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.framework.frameworkutils.Keywords.verifyText(Keywords.java:118)
	at com.framework.frameworkutils.Keywords.executeKeywords(Keywords.java:62)
	at com.framework.testcases.TC_001_Validate_Login_Page.TC_001_Validate_Login_Page(TC_001_Validate_Login_Page.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001_Validate_Login_Page -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.framework.testcases.TC_001_Validate_Login_Page@61001b64]" name="afterMethod" is-config="true" duration-ms="2119" started-at="2020-06-22T12:59:20Z" finished-at="2020-06-22T12:59:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC_001_Validate_Login_Page status=FAILURE method=TC_001_Validate_Login_Page.TC_001_Validate_Login_Page(java.util.Hashtable)[pri:0, instance:com.framework.testcases.TC_001_Validate_Login_Page@61001b64] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="reportClose()[pri:0, instance:com.framework.testcases.TC_001_Validate_Login_Page@61001b64]" name="reportClose" is-config="true" duration-ms="1" started-at="2020-06-22T12:59:22Z" finished-at="2020-06-22T12:59:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportClose -->
      </class> <!-- com.framework.testcases.TC_001_Validate_Login_Page -->
    </test> <!-- LoginTest -->
  </suite> <!-- RegressionTest -->
</testng-results>
